# Generated by Django 4.1.3 on 2023-04-28 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_friendly_name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('hex_value', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('serial_port_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('root_id', models.CharField(default='controly', max_length=30)),
                ('is_scene', models.BooleanField(default=False)),
                ('scene_name', models.CharField(blank=True, max_length=30)),
                ('state', models.BooleanField(default=None, null=True)),
                ('last_status', models.BooleanField(default=False)),
                ('changes', models.TextField(blank=True)),
                ('change_time', models.TimeField(blank=True, null=True)),
                ('device_icon_address', models.CharField(blank=True, default='', max_length=40)),
                ('animation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.animation')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.color')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_friendly_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code_name', models.CharField(max_length=100)),
                ('post_value', models.CharField(default='', max_length=100)),
                ('path', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.BooleanField(default=None, null=True)),
                ('animation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.animation')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.color')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.device')),
                ('recently_used_colors', models.ManyToManyField(blank=True, related_name='recently_scene', to='Main.color')),
                ('recently_used_colors_rest', models.ManyToManyField(blank=True, related_name='recently_rest_scene', to='Main.color')),
                ('rest_color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rest_color', to='Main.color')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='modules',
            field=models.ManyToManyField(to='Main.module'),
        ),
        migrations.AddField(
            model_name='device',
            name='recently_used_colors',
            field=models.ManyToManyField(blank=True, related_name='recently', to='Main.color'),
        ),
        migrations.AddField(
            model_name='device',
            name='recently_used_colors_rest',
            field=models.ManyToManyField(blank=True, related_name='recently_rest', to='Main.color'),
        ),
        migrations.AddField(
            model_name='device',
            name='rest_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='REST', to='Main.color'),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
