# Generated by Django 4.1.3 on 2023-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='other_info',
            field=models.TextField(blank=True),
        ),
    ]
